// app.js
App({
  onLaunch() {
    // 云开发功能已禁用，使用本地存储模式
    // if (wx.cloud) {
    //   try {
    //     wx.cloud.init({
    //       env: 'cloudbase-2g7pmtv3e63f7151', // 替换为你的环境ID
    //       traceUser: true,
    //     })
    //     console.log('云开发初始化成功')
    //   } catch (error) {
    //     console.error('云开发初始化失败:', error)
    //   }
    // } else {
    //   console.warn('当前环境不支持云开发')
    // }
    console.log('应用启动，使用本地存储模式')
    
    // 展示本地存储能力
    const logs = wx.getStorageSync('logs') || []
    logs.unshift(Date.now())
    wx.setStorageSync('logs', logs)

    // 检查是否需要重置词库（已禁用，保持默认词汇数据）
    // const RESET_FLAG = 'vocab_reset_2025_08_09'
    // try {
    //   if (!wx.getStorageSync(RESET_FLAG)) {
    //     wx.setStorageSync('words', [])
    //     wx.setStorageSync(RESET_FLAG, true)
    //     console.log('已清空词库（一次性重置）')
    //   }
    // } catch (e) {
    //   console.warn('重置词库失败:', e)
    // }

    // 从本地存储加载词汇数据
    this.loadVocabularyData()

    // 登录
    wx.login({
      success: res => {
        // 发送 res.code 到后台换取 openId, sessionKey, unionId
        console.log('登录成功', res)
      }
    })
  },

  // 从本地存储加载词汇数据
  loadVocabularyData() {
    try {
      // 首先尝试从本地存储加载词汇数据
      const storedWords = wx.getStorageSync('words')
      
      if (storedWords && storedWords.length > 0) {
        // 如果本地存储有数据，使用本地存储的数据
        console.log('从本地存储加载词汇数据，共', storedWords.length, '个词汇')
        this.globalData.words = this.normalizeCategories(storedWords)
      } else {
        // 如果本地存储没有数据，使用内置词汇数据
        console.log('本地存储无数据，使用内置词汇数据，共', this.globalData.words.length, '个词汇')
        this.globalData.words = this.normalizeCategories(this.globalData.words)
        // 保存内置数据到本地存储
        wx.setStorageSync('words', this.globalData.words)
        console.log('已保存内置词汇数据到本地存储')
      }
    } catch (error) {
      console.error('加载词汇数据失败:', error)
      // 如果加载失败，确保有默认数据
      if (!this.globalData.words || this.globalData.words.length === 0) {
        console.log('使用内置默认词汇数据')
      }
    }
  },
  
  // 统一规范分类名称，消除别名/空白差异
  normalizeCategories(words) {
    const aliasMap = new Map([
      ['GRE高频词', 'GRE高频词'],
      ['GRE高频词汇', 'GRE高频词'],
      ['TOEFL高频词', 'TOEFL高频词'],
      ['TOEFL高频词汇', 'TOEFL高频词'],
      ['AI专业词汇', 'AI专业词汇'],
      ['AI领域常用及专有词汇', 'AI专业词汇'],
      ['AI领域内常用词和专有词', 'AI专业词汇'],
      ['IELTS高频词', 'IELTS高频词'],
      ['IELTS高频词汇', 'IELTS高频词']
    ])
    return (words || []).map(w => ({
      ...w,
      category: aliasMap.get((w.category || '').trim()) || 'AI专业词汇'
    }))
  },
  
  // 添加云数据库操作方法
  async syncWordsToCloud() {
    try {
      const db = wx.cloud.database()
      const words = this.globalData.words
      
      // 批量上传词汇到云数据库
      for (let word of words) {
        await db.collection('vocabulary').add({
          data: word
        })
      }
      console.log('词汇同步到云端成功')
    } catch (error) {
      console.error('同步失败:', error)
    }
  },
  
  // 从云端获取词汇数据
  async getWordsFromCloud() {
    try {
      const db = wx.cloud.database()
      const result = await db.collection('vocabulary').get()
      console.log('从云端获取词汇成功:', result.data.length, '个词汇')
      return result.data
    } catch (error) {
      console.error('从云端获取词汇失败:', error)
      return []
    }
  },
  
  // 更新云端词汇数据
  async updateWordInCloud(wordId, updateData) {
    try {
      const db = wx.cloud.database()
      await db.collection('vocabulary').doc(wordId).update({
        data: updateData
      })
      console.log('云端词汇更新成功')
    } catch (error) {
      console.error('云端词汇更新失败:', error)
    }
  },
  
  // 删除云端词汇
  async deleteWordFromCloud(wordId) {
    try {
      const db = wx.cloud.database()
      await db.collection('vocabulary').doc(wordId).remove()
      console.log('云端词汇删除成功')
    } catch (error) {
      console.error('云端词汇删除失败:', error)
    }
  },
  globalData: {
    userInfo: null,
    // 词汇数据 - 从Attention Is All You Need论文中提取
        // 词汇数据 - 从论文中提取
    words: [
      {
        id: 1,
        word: 'Considerably',
        englishMeaning: 'By a notably large amount or to a notably large extent; significantly.',
        meaning: '相当大地，非常 (adverb)',
        partOfSpeech: 'adverb',
        pronunciation: '/kənˈsɪd.ə.r.ə.bli/',
        sentence: 'On the test data, we achieved top-1 and top-5 error rates of 37.5% and 17.0% which is considerably better than the previous state-of-the-art.',
        translation: '在测试数据上，我们取得了37.5%的top-1错误率和17.0%的top-5错误率，这比之前的最佳水平要好得多。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 2,
        word: 'Prohibitively',
        englishMeaning: 'To an extent that forbids or prevents something.',
        meaning: '(价格等)过高地，令人望而却步地 (adverb)',
        partOfSpeech: 'adverb',
        pronunciation: '/proʊˈhɪb.ə.t̬ɪv.li/',
        sentence: 'Despite the attractive qualities of CNNs, and despite the relative efficiency of their local architecture, they have still been prohibitively expensive to apply in large scale to high-resolution images.',
        translation: '尽管卷积神经网络具有吸引人的特性，并且其局部架构相对高效，但将它们大规模应用于高分辨率图像仍然是极其昂贵的。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 3,
        word: 'Inherent',
        englishMeaning: 'Existing in something as a permanent, essential, or characteristic attribute.',
        meaning: '固有的，内在的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ɪnˈhɪr.ənt/',
        sentence: 'We wrote a highly-optimized GPU implementation of 2D convolution and all the other operations inherent in training convolutional neural networks, which we make available publicly.',
        translation: '我们编写了一个高度优化的GPU实现，用于2D卷积以及训练卷积神经网络所固有的所有其他操作，并将其公开。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'GRE高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 4,
        word: 'Ambiguity',
        englishMeaning: 'The quality of being open to more than one interpretation; inexactness.',
        meaning: '模棱两可，不明确 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌæm.bɪˈɡjuː.ə.t̬i/',
        sentence: 'In some cases (grille, cherry) there is genuine ambiguity about the intended focus of the photograph.',
        translation: '在某些情况下（例如格栅、樱桃），照片的预期焦点确实存在模棱两可之处。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 5,
        word: 'Ultimately',
        englishMeaning: 'In the end; finally.',
        meaning: '最终，根本上 (adverb)',
        partOfSpeech: 'adverb',
        pronunciation: '/ˈʌl.tə.mət.li/',
        sentence: 'Ultimately we would like to use very large and deep convolutional nets on video sequences where the temporal structure provides very helpful information that is missing or far less obvious in static images.',
        translation: '最终，我们希望在视频序列上使用非常大且深的卷积网络，其中时间结构提供了在静态图像中缺失或远不明显的非常有用的信息。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 6,
        word: 'Efficient',
        englishMeaning: 'Achieving maximum productivity with minimum wasted effort or expense.',
        meaning: '高效的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ɪˈfɪʃ.ənt/',
        sentence: 'To make training faster, we used non-saturating neurons and a very efficient GPU implementation of the convolution operation.',
        translation: '为了加快训练速度，我们使用了非饱和神经元和一种非常高效的卷积运算GPU实现。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 7,
        word: 'Augment',
        englishMeaning: 'To make something greater by adding to it; to increase.',
        meaning: '增加，增强 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ɑːɡˈment/',
        sentence: 'Simple recognition tasks can be solved quite well with datasets of this size, especially if they are augmented with label-preserving transformations.',
        translation: '对于这种规模的数据集，简单的识别任务可以很好地解决，特别是如果通过保留标签的变换来增强数据。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 8,
        word: 'Capacity',
        englishMeaning: 'The ability or power to do, experience, or understand something.',
        meaning: '容量，能力 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/kəˈpæs.ə.t̬i/',
        sentence: 'Their capacity can be controlled by varying their depth and breadth, and they also make strong and mostly correct assumptions about the nature of images.',
        translation: '它们的能力可以通过改变其深度和广度来控制，并且它们对图像的性质做出了强有力且基本正确的假设。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 9,
        word: 'Facilitate',
        englishMeaning: 'To make an action or process easy or easier.',
        meaning: '促进，使便利 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/fəˈsɪl.ə.teɪt/',
        sentence: 'Luckily, current GPUs, paired with a highly-optimized implementation of 2D convolution, are powerful enough to facilitate the training of interestingly-large CNNs...',
        translation: '幸运的是，当前的GPU，配上一个高度优化的2D卷积实现，其功能强大到足以促进那些规模大到有趣的卷积神经网络的训练...',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 10,
        word: 'Scheme',
        englishMeaning: 'A large-scale systematic plan or arrangement for attaining a particular object or putting a particular idea into effect.',
        meaning: '方案，计划 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/skiːm/',
        sentence: 'Without this scheme, our network suffers from substantial overfitting, which would have forced us to use much smaller networks.',
        translation: '如果没有这个方案，我们的网络会遭受严重的过拟合，这将迫使我们使用小得多的网络。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 11,
        word: 'Initialize',
        englishMeaning: 'To set the starting value of a variable or process.',
        meaning: '初始化 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ɪˈnɪʃ.ə.laɪz/',
        sentence: 'We initialized the weights in each layer from a zero-mean Gaussian distribution with standard deviation 0.01.',
        translation: '我们从一个均值为零、标准差为0.01的高斯分布中初始化了每一层的权重。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 12,
        word: 'Qualitative',
        englishMeaning: 'Relating to, measuring, or measured by the quality of something rather than its quantity.',
        meaning: '定性的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ˈkwɑː.lə.teɪ.t̬ɪv/',
        sentence: 'In the left panel of Figure 4 we qualitatively assess what the network has learned by computing its top-5 predictions on eight test images.',
        translation: '在图4的左侧面板中，我们通过计算网络对八张测试图像的top-5预测，来定性地评估网络学到了什么。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 13,
        word: 'Approach',
        englishMeaning: 'A way of dealing with a situation or problem.',
        meaning: '方法，途径 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/əˈproʊtʃ/',
        sentence: 'Current approaches to object recognition make essential use of machine learning methods.',
        translation: '当前的物体识别方法主要利用机器学习方法。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 14,
        word: 'Technique',
        englishMeaning: 'A way of carrying out a particular task, especially the execution or performance of an artistic work or a scientific procedure.',
        meaning: '技术，技巧 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/tekˈniːk/',
        sentence: 'To improve their performance, we can collect larger datasets, learn more powerful models, and use better techniques for preventing overfitting.',
        translation: '为了提升它们的性能，我们可以收集更大的数据集，学习更强大的模型，以及使用更好的技术来防止过拟合。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'IELTS高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 15,
        word: 'Consist of',
        englishMeaning: 'To be composed or made up of.',
        meaning: '由…组成 (phrasal verb)',
        partOfSpeech: 'phrasal verb',
        pronunciation: '/kənˈsɪst əv/',
        sentence: 'The neural network, which has 60 million parameters and 650,000 neurons, consists of five convolutional layers...',
        translation: '这个拥有6000万参数和65万个神经元的神经网络，由五个卷积层组成...',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'IELTS高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 16,
        word: 'Impose',
        englishMeaning: 'To force an unwelcome decision or ruling on someone.',
        meaning: '强加，施加 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ɪmˈpoʊz/',
        sentence: 'Although the 1000 classes of ILSVRC make each training example impose 10 bits of constraint on the mapping from image to label, this turns out to be insufficient to learn so many parameters without considerable overfitting.',
        translation: '尽管ILSVRC的1000个类别使得每个训练样本对从图像到标签的映射施加了10比特的约束，但这对于学习如此多的参数而没有相当大的过拟合来说是不足够的。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 17,
        word: 'Convention',
        englishMeaning: 'A way in which something is usually done.',
        meaning: '惯例，常规 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/kənˈven.ʃən/',
        sentence: 'On this dataset we follow the convention in the literature of using half of the images for training and half for testing.',
        translation: '在这个数据集上，我们遵循文献中的惯例，即使用一半的图像进行训练，一半进行测试。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'IELTS高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 18,
        word: 'Overfitting',
        englishMeaning: 'The production of an analysis that corresponds too closely or exactly to a particular set of data, and may therefore fail to fit additional data or predict future observations reliably.',
        meaning: '过拟合 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌoʊ.vɚˈfɪt̬.ɪŋ/',
        sentence: 'To reduce overfitting in the fully-connected layers we employed a recently-developed regularization method called dropout...',
        translation: '为了减少全连接层中的过拟合，我们采用了一种最近开发的名为dropout的正则化方法...',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 19,
        word: 'Regularization',
        englishMeaning: 'A process in machine learning that adds a penalty term to the objective function to discourage complex models, thus avoiding overfitting.',
        meaning: '正则化 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌreɡ.jə.ləˈzeɪ.ʃən/',
        sentence: 'To reduce overfitting in the fully-connected layers we employed a recently-developed regularization method called dropout that proved to be very effective.',
        translation: '为了减少全连接层中的过拟合，我们采用了一种最近开发的名为dropout的正则化方法，它被证明非常有效。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 20,
        word: 'Softmax',
        englishMeaning: 'A function that takes as input a vector of K real numbers, and normalizes it into a probability distribution consisting of K probabilities proportional to the exponentials of the input numbers.',
        meaning: 'Softmax函数 (归一化指数函数) (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈsɑːft.mæks/',
        sentence: 'The neural network...consists of five convolutional layers...and three fully-connected layers with a final 1000-way softmax.',
        translation: '该神经网络...由五个卷积层...和三个带有最终1000路softmax的全连接层组成。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 21,
        word: 'Max-pooling',
        englishMeaning: 'A pooling operation that calculates the maximum value for patches of a feature map, and uses it to create a downsampled feature map.',
        meaning: '最大池化 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/mæks ˈpuː.lɪŋ/',
        sentence: 'The neural network... consists of five convolutional layers, some of which are followed by max-pooling layers...',
        translation: '该神经网络...由五个卷积层组成，其中一些层后面跟着最大池化层...',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 22,
        word: 'Dropout',
        englishMeaning: 'A regularization technique for neural networks that prevents co-adaptation of neurons by setting the output of each hidden neuron to zero with a certain probability.',
        meaning: 'Dropout (随机失活) (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈdrɑːp.aʊt/',
        sentence: 'The recently-introduced technique, called dropout, consists of setting to zero the output of each hidden neuron with probability 0.5.',
        translation: '最近引入的这项名为dropout的技术，其内容是以0.5的概率将每个隐藏神经元的输出设置为零。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 23,
        word: 'Fully-connected layer',
        englishMeaning: 'A layer in an artificial neural network in which every neuron in the layer is connected to every neuron in the preceding layer.',
        meaning: '全连接层 (noun phrase)',
        partOfSpeech: 'noun phrase',
        pronunciation: '/ˈfʊl.i kəˈnek.tɪd ˈleɪ.ɚ/',
        sentence: 'To reduce overfitting in the fully-connected layers we employed a recently-developed regularization method called dropout...',
        translation: '为了减少全连接层中的过拟合，我们采用了一种最近开发的名为dropout的正则化方法...',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 24,
        word: 'Back-propagation',
        englishMeaning: 'An algorithm for supervised learning of artificial neural networks using gradient descent, where the error is back-propagated through the network to adjust weights.',
        meaning: '反向传播 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/bæk ˌprɑː.pəˈɡeɪ.ʃən/',
        sentence: 'The neurons which are dropped out in this way do not contribute to the forward pass and do not participate in back-propagation.',
        translation: '以这种方式被丢弃的神经元既不参与前向传播，也不参与反向传播。',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 25,
        word: 'Hyper-parameter',
        englishMeaning: 'A parameter whose value is used to control the learning process, and which is set before the learning process begins.',
        meaning: '超参数 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈhaɪ.pɚ pəˈræm.ə.t̬ɚ/',
        sentence: 'The constants k, n, α, and β are hyper-parameters whose values are determined using a validation set...',
        translation: '常数k, n, α, 和β是超参数，其值通过一个验证集来确定...',
        paperTitle: 'ImageNet Classification with Deep Convolutional Neural Networks',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 26,
        word: 'Dominant',
        englishMeaning: 'Most important, powerful, or influential.',
        meaning: '占主导地位的',
        partOfSpeech: 'adjective',
        pronunciation: '/ˈdɑː.mə.nənt/',
        sentence: 'The **dominant** sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder.',
        translation: '主流的序列转换模型是基于复杂的循环或卷积神经网络，其中包括一个编码器和一个解码器。',
        paperTitle: 'Attention is all you need',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 27,
        word: 'Fundamental',
        englishMeaning: 'Forming a necessary base or core; of central importance.',
        meaning: '基础的，根本的',
        partOfSpeech: 'adjective',
        pronunciation: '/ˌfʌn.dəˈmen.t̬əl/',
        sentence: 'The **fundamental** constraint of sequential computation, however, remains.',
        translation: '然而，顺序计算的根本性制约依然存在。',
        paperTitle: 'Attention is all you need',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 28,
        word: 'Generalize',
        englishMeaning: 'To make a general or broad statement by inferring from specific cases; to apply a model successfully to new data.',
        meaning: '泛化，归纳',
        partOfSpeech: 'verb',
        pronunciation: '/ˈdʒen.ə.rəl.aɪz/',
        sentence: 'We show that the Transformer **generalizes** well to other tasks by applying it successfully to English constituency parsing both with large and limited training data.',
        translation: '我们通过将Transformer成功应用于大型和有限训练数据的英语成分句法分析，表明它能很好地泛化到其他任务。',
        paperTitle: 'Attention is all you need',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 29,
        word: 'Propose',
        englishMeaning: 'To put forward an idea or plan for consideration or discussion by others.',
        meaning: '提议，提出',
        partOfSpeech: 'verb',
        pronunciation: '/prəˈpoʊz/',
        sentence: 'We **propose** a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
        translation: '我们提出了一种新的、简单的网络架构——Transformer，它完全基于注意力机制，彻底摒弃了循环和卷积。',
        paperTitle: 'Attention is all you need',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 30,
        word: 'Superior',
        englishMeaning: 'Higher in rank, status, or quality.',
        meaning: '更好的，优越的',
        partOfSpeech: 'adjective',
        pronunciation: '/səˈpɪr.i.ɚ/',
        sentence: 'Experiments on two machine translation tasks show these models to be **superior** in quality while being more parallelizable and requiring significantly less time to train.',
        translation: '在两项机器翻译任务上的实验表明，这些模型在质量上更为优越，同时更易于并行化，训练所需时间也显著减少。',
        paperTitle: 'Attention is all you need',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 31,
        word: 'Achieve',
        englishMeaning: 'To successfully bring about or reach a desired objective, level, or result by effort, skill, or courage.',
        meaning: '实现，达到',
        partOfSpeech: 'verb',
        pronunciation: '/əˈtʃiːv/',
        sentence: 'Our model **achieves** 28.4 BLEU on the WMT 2014 English-to-German translation task, improving over the existing best results...',
        translation: '我们的模型在WMT 2014英德翻译任务上取得了28.4的BLEU得分，比现有的最佳结果有所提升...',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 32,
        word: 'Component',
        englishMeaning: 'A part or element of a larger whole.',
        meaning: '组件，组成部分',
        partOfSpeech: 'noun',
        pronunciation: '/kəmˈpoʊ.nənt/',
        sentence: 'To evaluate the importance of different **components** of the Transformer, we varied our base model in different ways....',
        translation: '为了评估Transformer不同组件的重要性，我们以不同方式改变了我们的基础模型....',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 33,
        word: 'Establish',
        englishMeaning: 'To set up on a firm or permanent basis; to show something to be true or certain by determining the facts.',
        meaning: '建立，确立',
        partOfSpeech: 'verb',
        pronunciation: '/ɪˈstæb.lɪʃ/',
        sentence: 'On the WMT 2014 English-to-French translation task, our model **establishes** a new single-model state-of-the-art BLEU score of 41.8....',
        translation: '在WMT 2014英法翻译任务上，我们的模型创造了单模型41.8的BLEU得分新纪录....',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 34,
        word: 'Evaluate',
        englishMeaning: 'To form an idea of the amount, number, or value of; to assess.',
        meaning: '评估，评价',
        partOfSpeech: 'verb',
        pronunciation: '/ɪˈvæl.ju.eɪt/',
        sentence: 'To **evaluate** the importance of different components of the Transformer, we varied our base model in different ways....',
        translation: '为了评估Transformer不同组件的重要性，我们以不同方式改变了我们的基础模型....',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 35,
        word: 'Implement',
        englishMeaning: 'To put a decision, plan, or agreement into effect.',
        meaning: '实现，实施',
        partOfSpeech: 'verb',
        pronunciation: '/ˈɪm.plə.ment/',
        sentence: 'We **implement** this inside of scaled dot-product attention by masking out all values in the input of the softmax which correspond to illegal connections.',
        translation: '我们通过在缩放点积注意力内部屏蔽掉所有对应非法连接的softmax输入值来实现这一点。',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 36,
        word: 'Parameter',
        englishMeaning: 'A numerical or other measurable factor forming one of a set that defines a system or sets the conditions of its operation.',
        meaning: '参数',
        partOfSpeech: 'noun',
        pronunciation: '/pəˈræm.ə.t̬ɚ/',
        sentence: 'While the linear transformations are the same across different positions, they use different **parameters** from layer to layer.',
        translation: '虽然线性变换在不同位置上是相同的，但它们在不同层之间使用不同的参数。',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 37,
        word: 'Significant',
        englishMeaning: 'Sufficiently great or important to be worthy of attention; noteworthy.',
        meaning: '显著的，重要的',
        partOfSpeech: 'adjective',
        pronunciation: '/sɪɡˈnɪf.ə.kənt/',
        sentence: 'Recent work has achieved **significant** improvements in computational efficiency through factorization tricks and conditional computation....',
        translation: '近期的工作通过因式分解技巧和条件计算，在计算效率上取得了显著的提升....',
        paperTitle: 'Attention is all you need',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 38,
        word: 'Approach',
        englishMeaning: 'A way of dealing with a situation or problem.',
        meaning: '方法，方式',
        partOfSpeech: 'noun',
        pronunciation: '/əˈproʊtʃ/',
        sentence: 'Recurrent neural networks... have been firmly established as state of the art **approaches** in sequence modeling and transduction problems....',
        translation: '循环神经网络...已被公认为是在序列建模和转换问题上的最佳方法....',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 39,
        word: 'Architecture',
        englishMeaning: 'The complex or carefully designed structure of something.',
        meaning: '架构，结构',
        partOfSpeech: 'noun',
        pronunciation: '/ˈɑːr.kə.tek.tʃɚ/',
        sentence: 'We propose a new simple network **architecture**, the Transformer, based solely on attention mechanisms....',
        translation: '我们提出了一种新的、简单的网络架构——Transformer，它完全基于注意力机制....',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 40,
        word: 'Consist',
        englishMeaning: 'To be composed or made up of.',
        meaning: '由…组成',
        partOfSpeech: 'verb',
        pronunciation: '/kənˈsɪst/',
        sentence: 'This **consists** of two linear transformations with a ReLU activation in between.',
        translation: '这由两个线性变换和一个位于它们之间的ReLU激活函数组成。',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 41,
        word: 'Despite',
        englishMeaning: 'Without being affected by; in spite of.',
        meaning: '尽管，虽然',
        partOfSpeech: 'preposition',
        pronunciation: '/dɪˈspaɪt/',
        sentence: 'Our results in Table 4 show that **despite** the lack of task-specific tuning our model performs surprisingly well....',
        translation: '表4中的结果显示，尽管缺乏针对特定任务的调优，我们的模型表现得出人意料地好....',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 42,
        word: 'Employ',
        englishMeaning: 'To make use of.',
        meaning: '使用，采用',
        partOfSpeech: 'verb',
        pronunciation: '/ɪmˈplɔɪ/',
        sentence: 'We **employ** a residual connection around each of the two sub-layers, followed by layer normalization.',
        translation: '我们在每个子层的周围都使用了一个残差连接，之后再进行层归一化。',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 43,
        word: 'Require',
        englishMeaning: 'To need something or make something necessary.',
        meaning: '需要，要求',
        partOfSpeech: 'verb',
        pronunciation: '/rɪˈkwaɪər/',
        sentence: 'Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and **requiring** significantly less time to train.',
        translation: '在两项机器翻译任务上的实验表明，这些模型在质量上更为优越，同时更易于并行化，训练所需时间也显著减少。',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 44,
        word: 'Semantic',
        englishMeaning: 'Relating to meaning in language or logic.',
        meaning: '语义的',
        partOfSpeech: 'adjective',
        pronunciation: '/səˈmæn.t̬ɪk/',
        sentence: 'Not only do individual attention heads clearly learn to perform different tasks, many appear to exhibit behavior related to the syntactic and **semantic** structure of the sentences.',
        translation: '各个注意力头不仅清晰地学会了执行不同的任务，许多头似乎还表现出与句子的句法和语义结构相关的行为。',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 45,
        word: 'Structure',
        englishMeaning: 'The arrangement of and relations between the parts or elements of something complex.',
        meaning: '结构',
        partOfSpeech: 'noun',
        pronunciation: '/ˈstrʌk.tʃɚ/',
        sentence: 'Most competitive neural sequence transduction models have an encoder-decoder **structure**.',
        translation: '大多数有竞争力的神经序列转换模型都具有编码器-解码器结构。',
        paperTitle: 'Attention is all you need',
        category: 'IELTS高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 46,
        word: 'Attention Mechanism',
        englishMeaning: 'A technique that allows a neural network to focus on specific parts of an input sequence when generating an output.',
        meaning: '注意力机制',
        partOfSpeech: 'noun phrase',
        pronunciation: '/əˈten.ʃən ˈmek.ə.nɪ.zəm/',
        sentence: 'The best performing models also connect the encoder and decoder through an **attention mechanism**.',
        translation: '表现最好的模型还通过一个注意力机制来连接编码器和解码器。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 47,
        word: 'Auto-Regressive',
        englishMeaning: 'A model where the prediction for a given time step is generated based on the outputs from previous time steps.',
        meaning: '自回归',
        partOfSpeech: 'adjective',
        pronunciation: '/ˌɔː.t̬oʊ.rɪˈɡres.ɪv/',
        sentence: 'At each step the model is **auto-regressive**, consuming the previously generated symbols as additional input when generating the next.',
        translation: '在每一步中，模型都是自回归的，它会将先前生成的符号作为额外输入来生成下一个符号。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 48,
        word: 'Decoder',
        englishMeaning: 'The part of an encoder-decoder model that generates the output sequence from the encoded representation.',
        meaning: '解码器',
        partOfSpeech: 'noun',
        pronunciation: '/diːˈkoʊ.dɚ/',
        sentence: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a **decoder**.',
        translation: '主流的序列转换模型是基于复杂的循环或卷积神经网络，其中包括一个编码器和一个解码器。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 49,
        word: 'Embedding',
        englishMeaning: 'A learned representation for discrete items like words, mapping them to vectors of continuous numbers.',
        meaning: '嵌入',
        partOfSpeech: 'noun',
        pronunciation: '/ɪmˈbed.ɪŋ/',
        sentence: 'To facilitate these residual connections, all sub-layers in the model, as well as the **embedding** layers, produce outputs of dimension dmodel=512.',
        translation: '为了方便这些残差连接，模型中所有的子层以及嵌入层都产生维度为dmodel=512的输出。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 50,
        word: 'Encoder',
        englishMeaning: 'The part of an encoder-decoder model that processes the input sequence and converts it into a continuous representation.',
        meaning: '编码器',
        partOfSpeech: 'noun',
        pronunciation: '/ɪnˈkoʊ.dɚ/',
        sentence: 'The best performing models also connect the **encoder** and decoder through an attention mechanism.',
        translation: '表现最好的模型还通过一个注意力机制来连接编码器和解码器。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 51,
        word: 'Feed-Forward Network',
        englishMeaning: 'A type of artificial neural network where connections between units do not form a cycle.',
        meaning: '前馈网络',
        partOfSpeech: 'noun phrase',
        pronunciation: '/ˈfiːdˌfɔːr.wɚd ˈnet.wɝːk/',
        sentence: 'The first is a multi-head self-attention mechanism, and the second is a simple, position-wise fully connected **feed-forward network**.',
        translation: '第一个是多头自注意力机制，第二个是简单的、按位置全连接的前馈网络。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 52,
        word: 'Multi-Head Attention',
        englishMeaning: 'An attention mechanism that runs multiple attention functions in parallel, allowing the model to jointly attend to information from different representation subspaces.',
        meaning: '多头注意力',
        partOfSpeech: 'noun phrase',
        pronunciation: '/ˈmʌl.ti hed əˈten.ʃən/',
        sentence: '**Multi-head attention** allows the model to jointly attend to information from different representation subspaces at different positions.',
        translation: '多头注意力使得模型能够在不同位置上共同关注来自不同表示子空间的信息。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 53,
        word: 'Positional Encoding',
        englishMeaning: 'A technique to inject information about the relative or absolute position of tokens in a sequence.',
        meaning: '位置编码',
        partOfSpeech: 'noun phrase',
        pronunciation: '/pəˈzɪʃ.ən.əl ɪnˈkoʊ.dɪŋ/',
        sentence: 'The **positional encodings** have the same dimension dmodel as the embeddings, so that the two can be summed.',
        translation: '位置编码与嵌入具有相同的维度dmodel，因此两者可以相加。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 54,
        word: 'Self-Attention',
        englishMeaning: 'An attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence.',
        meaning: '自注意力',
        partOfSpeech: 'noun',
        pronunciation: '/self əˈten.ʃən/',
        sentence: '**Self-attention**, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence.',
        translation: '自注意力，有时也称为内部注意力，是一种关联单个序列不同位置以计算该序列表示的注意力机制。',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 55,
        word: 'Transduction',
        englishMeaning: 'The process of converting an input sequence into an output sequence, as seen in tasks like machine translation.',
        meaning: '转换，转导',
        partOfSpeech: 'noun',
        pronunciation: '/trænsˈdʌk.ʃən/',
        sentence: 'The dominant sequence **transduction** models are based on complex recurrent or convolutional neural networks....',
        translation: '主流的序列转换模型是基于复杂的循环或卷积神经网络....',
        paperTitle: 'Attention is all you need',
        category: 'AI专业词汇',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 56,
        word: 'Subsequent',
        englishMeaning: 'Coming after something in time; following.',
        meaning: '随后的，后来的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ˈsʌb.sɪ.kwənt/',
        sentence: 'The initial model used to generate data for the RM is the SFT model, but subsequent reward model data is generated with the PPO models from the current best policy.',
        translation: '用于为奖励模型生成数据的初始模型是SFT模型，但随后的奖励模型数据是使用当前最佳策略的PPO模型生成的。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 57,
        word: 'Feasible',
        englishMeaning: 'Possible to do easily or conveniently.',
        meaning: '可行的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ˈfiː.zə.bəl/',
        sentence: 'This is much more data-efficient than training on demonstrations alone; for summarization, we would need over 50 times more human demonstrations for the SFT model to reach the same quality as PPO, and it’s not clear if this is even feasible.',
        translation: '这比单独在演示数据上训练要高效得多；对于摘要任务，SFT模型需要超过50倍的人类演示数据才能达到与PPO相同的质量，而且这甚至是否可行都还不清楚。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'GRE高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 58,
        word: 'Analogous',
        englishMeaning: 'Comparable in certain respects, typically in a way that makes clearer the nature of the things compared.',
        meaning: '类似的，可类比的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/əˈnæl.ə.ɡəs/',
        sentence: 'Our methodology is analogous to that of Ziegler et al. (2019) and Stiennon et al. (2020), who use this technique to fine-tune language models on the tasks of summarization and text continuation.',
        translation: '我们的方法论与Ziegler等人（2019）和Stiennon等人（2020）的方法类似，他们使用这项技术在摘要和文本续写任务上微调语言模型。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 59,
        word: 'Aggregate',
        englishMeaning: 'Formed or calculated by the combination of many separate units or items; total.',
        meaning: '合计的，总体的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ˈæɡ.rə.ɡət/',
        sentence: 'On an aggregate level, our labelers significantly prefer InstructGPT outputs over outputs from GPT-3.',
        translation: '在总体层面上，我们的标注员明显更偏好InstructGPT的输出，而不是GPT-3的输出。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'GRE高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 60,
        word: 'Distribution',
        englishMeaning: 'The way in which something is shared out among a group or spread over an area.',
        meaning: '分布 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌdɪs.trɪˈbjuː.ʃən/',
        sentence: 'We collect a dataset of human-written demonstrations of the desired output behavior, and use this to fine-tune GPT-3 on a diverse distribution of tasks.',
        translation: '我们收集了一个由人类编写的、展示期望输出行为的演示数据集，并用它在一个多样化的任务分布上对GPT-3进行微调。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 61,
        word: 'Demonstration',
        englishMeaning: 'An act of showing that something exists or is true by giving proof or evidence.',
        meaning: '演示，证明 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌdem.ənˈstreɪ.ʃən/',
        sentence: 'We train our models using a combination of supervised learning on human demonstrations, and reinforcement learning on a dataset of human-labeled comparisons between two model outputs.',
        translation: '我们结合在人类演示数据上的监督学习，以及在一个带有人类标注的模型双输出对比数据集上的强化学习来训练我们的模型。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 62,
        word: 'Initial',
        englishMeaning: 'Existing or occurring at the beginning.',
        meaning: '最初的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ɪˈnɪʃ.əl/',
        sentence: 'We start with a pretrained language model, and an initial set of human-written prompts and demonstrations of the desired behavior on these prompts.',
        translation: '我们从一个预训练的语言模型开始，以及一批初始的、由人类编写的提示和在这些提示上期望行为的演示。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 63,
        word: 'Generate',
        englishMeaning: 'To produce or create something.',
        meaning: '生成，产生 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈdʒen.ə.reɪt/',
        sentence: 'However, these models can also generate outputs that are untruthful, toxic, or simply not helpful to the user.',
        translation: '然而，这些模型也可能生成不真实、有害或对用户毫无帮助的输出。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 64,
        word: 'Obtain',
        englishMeaning: 'To get, acquire, or secure something.',
        meaning: '获得 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/əbˈteɪn/',
        sentence: 'We then collect a dataset of human-labeled comparisons between two model outputs to obtain a reward model.',
        translation: '然后，我们收集一个带有人类标注的模型双输出对比数据集，以获得一个奖励模型。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 65,
        word: 'Methodology',
        englishMeaning: 'A system of methods used in a particular area of study or activity.',
        meaning: '方法论 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌmeθ.əˈdɑː.lə.dʒi/',
        sentence: 'Our high-level methodology is shown in Figure 2 and described in detail in Section 3.',
        translation: '我们的高层方法论展示在图2中，并在第3节有详细描述。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 66,
        word: 'Policy',
        englishMeaning: 'In reinforcement learning, a strategy that the agent employs to determine the next action based on the current state.',
        meaning: '策略 (在强化学习中) (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈpɑː.lə.si/',
        sentence: 'The SFT model is initialized from the language model, the RM is initialized from the SFT model, and the PPO model is initialized from the SFT model; thus all three models contain the weights of the pretrained language model.',
        translation: 'SFT模型从语言模型初始化，奖励模型从SFT模型初始化，而PPO模型也从SFT模型初始化；因此所有三个模型都包含了预训练语言模型的权重。(注：PPO模型即策略模型)',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 67,
        word: 'Explicit',
        englishMeaning: 'Stated clearly and in detail, leaving no room for confusion or doubt.',
        meaning: '明确的，清晰的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ɪkˈsplɪs.ɪt/',
        sentence: 'In contrast, on the two public datasets we test on, our models show small regressions in performance; this is to be expected, as most public NLP datasets are designed to measure performance on a specific task, rather than how well a model follows explicit user instructions.',
        translation: '相反，在我们测试的两个公开数据集上，我们的模型表现出轻微的性能下降；这是预料之中的，因为大多数公开的NLP数据集旨在衡量特定任务的性能，而不是一个模型遵循明确用户指令的能力。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 68,
        word: 'Ethical',
        englishMeaning: 'Relating to moral principles or the branch of knowledge dealing with these.',
        meaning: '伦理的，道德的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ˈeθ.ɪ.kəl/',
        sentence: 'Making language models bigger does not inherently make them better at following a user’s intent. For example, large language models can generate outputs that are untruthful, toxic, or simply not helpful to the user. In other words, these models are not aligned with their users1.',
        translation: '将语言模型变得更大并不会使其在遵循用户意图方面本质上变得更好。例如，大型语言模型可能会生成不真实、有害或对用户毫无帮助的输出。换句话说，这些模型与用户是不对齐的。 (注：此句为背景描述，引出对齐的重要性，与伦理密切相关)',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 69,
        word: 'Paradigm',
        englishMeaning: 'A typical example or pattern of something; a model or framework.',
        meaning: '范式，典范 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈper.ə.daɪm/',
        sentence: 'The dominant paradigm has been to fine-tune these models on a narrow distribution of data, or on a specific NLP task.',
        translation: '主流范式一直是在一个狭窄的数据分布上或针对一个特定的NLP任务对这些模型进行微调。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 70,
        word: 'Utilize',
        englishMeaning: 'To make practical and effective use of.',
        meaning: '利用 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈjuː.t̬əl.aɪz/',
        sentence: 'A promising direction for aligning language models with user intent is reinforcement learning from human feedback, which utilizes human preferences as a reward signal to fine-tune models.',
        translation: '一个将语言模型与用户意图对齐的有前景的方向是基于人类反馈的强化学习，该方法利用人类偏好作为奖励信号来微调模型。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 71,
        word: 'Illustrative',
        englishMeaning: 'Serving as an example or explanation.',
        meaning: '作为例证的，解说性的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ɪˈlʌs.trə.t̬ɪv/',
        sentence: 'Illustrative user prompts from InstructGPT distribution.',
        translation: '来自InstructGPT分布的示例性用户提示。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 72,
        word: 'Alignment',
        englishMeaning: 'The process of ensuring that an AI system\'s behavior aligns with human values.',
        meaning: '对齐 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/əˈlaɪn.mənt/',
        sentence: 'This paper describes InstructGPT, a class of models that are trained to follow instructions, and are better aligned with user intent than GPT-3.',
        translation: '本文描述了InstructGPT，一类经过训练以遵循指令的模型，并且比GPT-3更能与用户意图对齐。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 73,
        word: 'Fine-tuning',
        englishMeaning: 'The process of taking a pre-trained model and training it further on a smaller, task-specific dataset.',
        meaning: '微调 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈfaɪnˌtuː.nɪŋ/',
        sentence: 'The primary technique for adapting these models to specific tasks is fine-tuning on a supervised dataset.',
        translation: '使这些模型适应特定任务的主要技术是在一个监督数据集上进行微调。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 74,
        word: 'Pre-training',
        englishMeaning: 'The initial phase of training a large model on a vast amount of unlabeled data to learn general representations of language or other data types.',
        meaning: '预训练 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌpriːˈtreɪ.nɪŋ/',
        sentence: 'These models are first trained on a large corpus of text data in a self-supervised way (pre-training), and then adapted to a specific task (fine-tuning).',
        translation: '这些模型首先在一个大型文本语料库上以自监督的方式进行训练（预训练），然后适应于特定任务（微调）。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 75,
        word: 'Prompt',
        englishMeaning: 'An input given to a language model to elicit a specific kind of response or to instruct it to perform a task.',
        meaning: '提示 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/prɑːmpt/',
        sentence: 'We collect a dataset of labeler-written prompts and prompts submitted through the OpenAI API.',
        translation: '我们收集了一个由标注员编写的提示以及通过OpenAI API提交的提示所组成的数据集。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 76,
        word: 'Hallucination',
        englishMeaning: 'In AI, the generation of information that is nonsensical, factually incorrect, or disconnected from the provided source data.',
        meaning: '幻觉 (指模型虚构信息) (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/həˌluː.səˈneɪ.ʃən/',
        sentence: 'This phenomenon is often called model ‘hallucination.’',
        translation: '这种现象通常被称为模型的“幻觉”。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'hard',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 77,
        word: 'Toxicity',
        englishMeaning: 'The quality of being harmful, offensive, or malicious, often used to describe language generated by AI.',
        meaning: '毒性 (指内容的有害性) (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/tɑːkˈsɪs.ə.t̬i/',
        sentence: 'To measure the toxicity of our model’s outputs, we use the RealToxicityPrompts dataset.',
        translation: '为了衡量我们模型输出的毒性，我们使用了RealToxicityPrompts数据集。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'medium',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 78,
        word: 'Bias',
        englishMeaning: 'In AI, systematic prejudice in the model\'s outputs or behavior.',
        meaning: '偏见 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈbaɪ.əs/',
        sentence: 'The goal of our bias evaluations is to understand how our models behave on inputs related to different demographic groups.',
        translation: '我们进行偏见评估的目标是了解我们的模型在处理与不同人口群体相关的输入时的行为。',
        paperTitle: 'Training language models to follow instructions with human feedback',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 79,
        word: 'Substantial',
        englishMeaning: 'Considerable in quantity or significance; large in amount.',
        meaning: '大量的，实质性的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/səbˈstæn.ʃəl/',
        sentence: 'Pre-trained neural language models have been shown to learn a substantial amount of in-depth knowledge from data.',
        translation: '预训练的神经语言模型已被证明能从数据中学到大量的深度知识。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'GRE高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 80,
        word: 'Provenance',
        englishMeaning: 'The place of origin or earliest known history of something.',
        meaning: '来源，出处 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈprɑː.və.nəns/',
        sentence: 'Additionally, providing provenance for their decisions and updating their world knowledge remain open research problems.',
        translation: '此外，为其决策提供来源依据以及更新其世界知识仍然是开放的研究问题。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'GRE高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 81,
        word: 'Mitigate',
        englishMeaning: 'To make something less severe, harmful, or painful.',
        meaning: '减轻，缓和 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈmɪt.ɪ.ɡeɪt/',
        sentence: 'RAG models can mitigate the problem of hallucination by providing access to external knowledge.',
        translation: 'RAG模型可以通过提供外部知识访问来减轻幻觉问题。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'GRE高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 82,
        word: 'Precisely',
        englishMeaning: 'Exactly or accurately; with exactness and accuracy.',
        meaning: '精确地 (adverb)',
        partOfSpeech: 'adverb',
        pronunciation: '/prɪˈsaɪs.li/',
        sentence: 'The model can precisely retrieve relevant documents for the given query.',
        translation: '模型可以精确地检索给定查询的相关文档。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 83,
        word: 'Formulation',
        englishMeaning: 'The way in which something is expressed or put into words.',
        meaning: '构想，公式化表达 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˌfɔːr.mjuˈleɪ.ʃən/',
        sentence: 'The formulation of the retrieval-augmented generation approach combines parametric and non-parametric memory.',
        translation: '检索增强生成方法的构想结合了参数化和非参数化记忆。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 84,
        word: 'Diverse',
        englishMeaning: 'Showing a great deal of variety; very different.',
        meaning: '多样的 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/daɪˈvɜːrs/',
        sentence: 'The model can access diverse sources of information through the retrieval mechanism.',
        translation: '模型可以通过检索机制访问多样化的信息源。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 85,
        word: 'Validate',
        englishMeaning: 'To check or prove the accuracy or validity of something.',
        meaning: '验证 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈvæl.ɪ.deɪt/',
        sentence: 'We validate our approach on multiple knowledge-intensive tasks.',
        translation: '我们在多个知识密集型任务上验证了我们的方法。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 86,
        word: 'Unify',
        englishMeaning: 'To combine or integrate into a single system or whole.',
        meaning: '统一，整合 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈjuː.nɪ.faɪ/',
        sentence: 'RAG unifies the retrieval and generation processes in a single model.',
        translation: 'RAG在单个模型中统一了检索和生成过程。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 87,
        word: 'Demonstrate',
        englishMeaning: 'To show or prove something clearly and convincingly.',
        meaning: '展示，证明 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈdem.ən.streɪt/',
        sentence: 'Our experiments demonstrate the effectiveness of the retrieval-augmented approach.',
        translation: '我们的实验证明了检索增强方法的有效性。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'TOEFL高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 88,
        word: 'Recipe',
        englishMeaning: 'A set of instructions or method for achieving a particular result.',
        meaning: '方案，方法 (引申义) (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/ˈres.ɪ.pi/',
        sentence: 'The paper provides a recipe for building effective retrieval-augmented models.',
        translation: '该论文提供了构建有效检索增强模型的方案。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'IELTS高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 89,
        word: 'Crucially',
        englishMeaning: 'In a way that is extremely important or decisive.',
        meaning: '至关重要地 (adverb)',
        partOfSpeech: 'adverb',
        pronunciation: '/ˈkruː.ʃəl.i/',
        sentence: 'Crucially, the model can access external knowledge during generation.',
        translation: '至关重要的是，模型在生成过程中可以访问外部知识。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'IELTS高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 90,
        word: 'Isolate',
        englishMeaning: 'To separate or set apart from others; to consider separately.',
        meaning: '孤立，单独考虑 (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈaɪ.sə.leɪt/',
        sentence: 'We isolate the effects of retrieval by comparing with baseline models.',
        translation: '我们通过与基线模型比较来孤立检索的效果。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'IELTS高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 91,
        word: 'Procedure',
        englishMeaning: 'A series of actions conducted in a certain order or manner.',
        meaning: '程序，步骤 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/prəˈsiː.dʒər/',
        sentence: 'The training procedure involves jointly optimizing the retriever and generator.',
        translation: '训练程序涉及联合优化检索器和生成器。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'IELTS高频词',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 92,
        word: 'Downstream Task',
        englishMeaning: 'A task that uses the output or features from a pre-trained model.',
        meaning: '下游任务 (noun phrase)',
        partOfSpeech: 'noun phrase',
        pronunciation: '/ˈdaʊn.striːm tæsk/',
        sentence: 'The model is evaluated on various downstream tasks.',
        translation: '模型在各种下游任务上进行评估。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 93,
        word: 'Parametric Memory',
        englishMeaning: 'Knowledge stored in the parameters of a neural network model.',
        meaning: '参数化记忆 (noun phrase)',
        partOfSpeech: 'noun phrase',
        pronunciation: '/ˌper.əˈmet.rɪk ˈmem.ər.i/',
        sentence: 'Parametric memory is stored in the model parameters.',
        translation: '参数化记忆存储在模型参数中。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 94,
        word: 'Non-parametric Memory',
        englishMeaning: 'Knowledge stored externally and accessed through retrieval mechanisms.',
        meaning: '非参数化记忆 (noun phrase)',
        partOfSpeech: 'noun phrase',
        pronunciation: '/nɒn ˌper.əˈmet.rɪk ˈmem.ər.i/',
        sentence: 'Non-parametric memory is accessed with a pre-trained neural retriever.',
        translation: '非参数化记忆通过预训练的神经检索器进行访问。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 95,
        word: 'Retriever',
        englishMeaning: 'A component that searches for and retrieves relevant information from a knowledge base.',
        meaning: '检索器 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/rɪˈtriː.vər/',
        sentence: 'The retriever component finds relevant documents for the input query.',
        translation: '检索器组件为输入查询找到相关文档。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 96,
        word: 'Extractive',
        englishMeaning: 'Relating to or involving the extraction of specific text segments from source documents.',
        meaning: '抽取式 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/ɪkˈstræk.tɪv/',
        sentence: 'We compare RAG to the popular extractive QA paradigm...',
        translation: '我们将RAG与流行的抽取式问答范式进行比较...',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 97,
        word: 'Abstractive',
        englishMeaning: 'Relating to or involving the generation of new text that may not appear verbatim in the source.',
        meaning: '抽象式，生成式 (adjective)',
        partOfSpeech: 'adjective',
        pronunciation: '/æbˈstræk.tɪv/',
        sentence: 'To test RAG\'s natural language generation (NLG) in a knowledge-intensive setting, we use the MSMARCO NLG task v2.1.',
        translation: '为了在知识密集型环境中测试RAG的自然语言生成（NLG）能力，我们使用了MSMARCO NLG v2.1任务。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 98,
        word: 'Marginalize',
        englishMeaning: 'To sum or integrate over a variable to obtain a marginal distribution.',
        meaning: '边缘化 (求边缘概率) (verb)',
        partOfSpeech: 'verb',
        pronunciation: '/ˈmɑːr.dʒɪ.nəl.aɪz/',
        sentence: 'For final prediction y, we treat z as a latent variable and marginalize over seq2seq predictions given different documents.',
        translation: '对于最终的预测y，我们将z视为一个潜变量，并在给定不同文档的情况下，对seq2seq的预测进行边缘化处理。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 99,
        word: 'Latent Variable',
        englishMeaning: 'A variable that is not directly observed but is inferred from other observed variables.',
        meaning: '潜变量，隐变量 (noun phrase)',
        partOfSpeech: 'noun phrase',
        pronunciation: '/ˈleɪ.tənt ˈver.i.ə.bəl/',
        sentence: 'To train the retriever and generator end-to-end, we treat the retrieved document as a latent variable.',
        translation: '为了端到端地训练检索器和生成器，我们将检索到的文档视为一个潜变量。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      },
      {
        id: 100,
        word: 'Ablation',
        englishMeaning: 'A study that removes components of a system to understand their contribution to performance.',
        meaning: '消融研究 (noun)',
        partOfSpeech: 'noun',
        pronunciation: '/əˈbleɪ.ʃən/',
        sentence: 'To assess the effectiveness of the retrieval mechanism, we run ablations where we freeze the retriever during training.',
        translation: '为了评估检索机制的有效性，我们进行了消融实验，在训练期间冻结了检索器。',
        paperTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        category: 'AI专业词汇',
        difficulty: 'easy',
        studyCount: 0,
        correctCount: 0,
        lastStudyTime: null,
        status: 'learning',
        weeklyStudyCount: 0
      }
    ]
  }
})