// 词汇更新数据
// 自动生成于: 2025-09-08T19:11:55.294437

const vocabularyUpdate = {
  "version": "20250908_191155",
  "vocabulary": [
    {
      "word": "ambiguity",
      "meaning": "歧义性",
      "englishMeaning": "the quality of being open to more than one interpretation",
      "pronunciation": "/ˌæmbɪˈɡjuːɪti/",
      "sentence": "Word Segmentation and Sense Ambiguity pose significant challenges in natural language understanding.",
      "translation": "分词和语义歧义性在自然语言理解中构成重大挑战。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282844",
      "id": 1
    },
    {
      "word": "pragmatic",
      "meaning": "实用的",
      "englishMeaning": "dealing with things sensibly and realistically",
      "pronunciation": "/præɡˈmætɪk/",
      "sentence": "Pragmatic Ambiguity refers to the uncertainty in interpreting user intent in real-world contexts.",
      "translation": "语用歧义性指的是在现实语境中解释用户意图时的不确定性。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282855",
      "id": 2
    },
    {
      "word": "robustness",
      "meaning": "鲁棒性",
      "englishMeaning": "the ability to withstand or overcome adverse conditions",
      "pronunciation": "/roʊˈbʌstnəs/",
      "sentence": "Robustness and Efficiency are critical requirements for production systems.",
      "translation": "鲁棒性和效率是生产系统的关键要求。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282860",
      "id": 3
    },
    {
      "word": "diversity",
      "meaning": "多样性",
      "englishMeaning": "the quality or state of having many different forms, types, ideas, etc.",
      "pronunciation": "/daɪˈvɜːrsəti/",
      "sentence": "Database size and diversity present significant challenges for model generalization.",
      "translation": "数据库大小和多样性对模型泛化提出了重大挑战。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282864",
      "id": 4
    },
    {
      "word": "complexity",
      "meaning": "复杂性",
      "englishMeaning": "the state or quality of being intricate or complicated",
      "pronunciation": "/kəmˈpleksəti/",
      "sentence": "Complexity of SQL queries ranges from simple single-table queries to complex multi-join operations.",
      "translation": "SQL查询的复杂性范围从简单的单表查询到复杂的多连接操作。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282867",
      "id": 5
    },
    {
      "word": "enhance",
      "meaning": "增强",
      "englishMeaning": "to increase or improve in quality, value, or extent",
      "pronunciation": "/ɪnˈhæns/",
      "sentence": "Large Language Model Enhanced Text-to-SQL Generation has shown remarkable progress.",
      "translation": "大语言模型增强的文本到SQL生成已显示出显著进展。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "TOEFL高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282871",
      "id": 6
    },
    {
      "word": "evaluation",
      "meaning": "评估",
      "englishMeaning": "the making of a judgment about the amount, number, or value of something",
      "pronunciation": "/ɪˌvæljuˈeɪʃn/",
      "sentence": "Evaluation metrics are crucial for assessing model performance.",
      "translation": "评估指标对于评估模型性能至关重要。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282874",
      "id": 7
    },
    {
      "word": "efficiency",
      "meaning": "效率",
      "englishMeaning": "the state or quality of being efficient",
      "pronunciation": "/ɪˈfɪʃnsi/",
      "sentence": "The system must balance between accuracy and computational efficiency.",
      "translation": "系统必须在准确性和计算效率之间取得平衡。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282878",
      "id": 8
    },
    {
      "word": "methodology",
      "meaning": "方法论",
      "englishMeaning": "a system of methods used in a particular area of study or activity",
      "pronunciation": "/ˌmeθəˈdɑːlədʒi/",
      "sentence": "The paper discusses various methodologies for Text-to-SQL conversion.",
      "translation": "本文讨论了文本到SQL转换的各种方法论。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282881",
      "id": 9
    },
    {
      "word": "preliminary",
      "meaning": "初步的",
      "englishMeaning": "preceding or done in preparation for something fuller or more important",
      "pronunciation": "/prɪˈlɪmɪneri/",
      "sentence": "The preliminaries section introduces basic concepts and definitions.",
      "translation": "预备知识部分介绍了基本概念和定义。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282884",
      "id": 10
    },
    {
      "word": "survey",
      "meaning": "综述",
      "englishMeaning": "a general view, examination, or description of someone or something",
      "pronunciation": "/ˈsɜːrveɪ/",
      "sentence": "This survey provides a comprehensive overview of LLM-enhanced Text-to-SQL methods.",
      "translation": "本综述提供了LLM增强的文本到SQL方法的全面概述。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "IELTS高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282888",
      "id": 11
    },
    {
      "word": "generation",
      "meaning": "生成",
      "englishMeaning": "the production or creation of something",
      "pronunciation": "/ˌdʒenəˈreɪʃn/",
      "sentence": "Text-to-SQL generation involves converting natural language queries into SQL commands.",
      "translation": "文本到SQL生成涉及将自然语言查询转换为SQL命令。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282891",
      "id": 12
    },
    {
      "word": "metric",
      "meaning": "指标",
      "englishMeaning": "a standard of measurement",
      "pronunciation": "/ˈmetrɪk/",
      "sentence": "Various evaluation metrics are used to assess SQL generation quality.",
      "translation": "使用各种评估指标来评估SQL生成质量。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "IELTS高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282893",
      "id": 13
    },
    {
      "word": "execution",
      "meaning": "执行",
      "englishMeaning": "the carrying out or performance of a plan, order, or course of action",
      "pronunciation": "/ˌeksɪˈkjuːʃn/",
      "sentence": "Execution Accuracy measures whether the generated SQL produces correct results.",
      "translation": "执行准确性衡量生成的SQL是否产生正确结果。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282896",
      "id": 14
    },
    {
      "word": "valid",
      "meaning": "有效的",
      "englishMeaning": "having a sound basis in logic or fact; reasonable or cogent",
      "pronunciation": "/ˈvælɪd/",
      "sentence": "Valid Efficiency Score evaluates both correctness and efficiency of generated queries.",
      "translation": "有效效率分数评估生成查询的正确性和效率。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "IELTS高频词",
      "difficulty": "easy",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282905",
      "id": 15
    },
    {
      "word": "fine-tuning",
      "meaning": "微调",
      "englishMeaning": "the process of adapting a pre-trained model to a specific task",
      "pronunciation": "/faɪn ˈtuːnɪŋ/",
      "sentence": "Fine-tuning pre-trained LLMs on domain-specific data improves Text-to-SQL performance.",
      "translation": "在领域特定数据上对预训练LLM进行微调可提高文本到SQL性能。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282908",
      "id": 16
    },
    {
      "word": "prompt engineering",
      "meaning": "提示工程",
      "englishMeaning": "the craft of designing effective input prompts for language models",
      "pronunciation": "/prɒmpt ˌendʒɪˈnɪərɪŋ/",
      "sentence": "Prompt engineering techniques significantly impact LLM performance in SQL generation.",
      "translation": "提示工程技术显著影响LLM在SQL生成中的性能。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282911",
      "id": 17
    },
    {
      "word": "language model",
      "meaning": "语言模型",
      "englishMeaning": "a probabilistic model that predicts the next word in a sequence",
      "pronunciation": "/ˈlæŋɡwɪdʒ ˈmɒdl/",
      "sentence": "Large Language Models have revolutionized natural language processing tasks.",
      "translation": "大语言模型已经革命性地改变了自然语言处理任务。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282913",
      "id": 18
    },
    {
      "word": "semantic parsing",
      "meaning": "语义解析",
      "englishMeaning": "the process of converting natural language into machine-understandable representations",
      "pronunciation": "/sɪˈmæntɪk ˈpɑːrsɪŋ/",
      "sentence": "Semantic parsing is at the core of Text-to-SQL systems.",
      "translation": "语义解析是文本到SQL系统的核心。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282916",
      "id": 19
    },
    {
      "word": "query optimization",
      "meaning": "查询优化",
      "englishMeaning": "the process of improving the efficiency of database queries",
      "pronunciation": "/ˈkwɪəri ˌɒptɪmaɪˈzeɪʃn/",
      "sentence": "Query optimization techniques ensure generated SQL runs efficiently on databases.",
      "translation": "查询优化技术确保生成的SQL在数据库上高效运行。",
      "paperTitle": "Large Language Model Enhanced Text-to-SQL Generation: A Survey",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.282919",
      "id": 20
    },
    {
      "word": "delegation",
      "meaning": "授权，委托",
      "englishMeaning": "the process of giving control, authority, or a job to someone else",
      "pronunciation": "/ˌdɛlɪˈɡeɪʃən/",
      "sentence": "Delegation to AI has already begun to improve the efficiency of individual processes",
      "translation": "委托给AI已经开始提高单个流程的效率",
      "paperTitle": "The Agentic Economy",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284750",
      "id": 21
    },
    {
      "word": "disruptive",
      "meaning": "颠覆性的",
      "englishMeaning": "causing major change or disturbance",
      "pronunciation": "/dɪsˈrʌptɪv/",
      "sentence": "the more disruptive—and yet to be realized—impact of generative AI",
      "translation": "生成式AI更具颠覆性且尚未实现的影响",
      "paperTitle": "The Agentic Economy",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284757",
      "id": 22
    },
    {
      "word": "friction",
      "meaning": "摩擦，阻力",
      "englishMeaning": "disagreement or conflict between people or things",
      "pronunciation": "/ˈfrɪkʃən/",
      "sentence": "reduce the communication frictions between consumers and businesses",
      "translation": "减少消费者与企业之间的沟通摩擦",
      "paperTitle": "The Agentic Economy",
      "category": "GRE高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284760",
      "id": 23
    },
    {
      "word": "flexibly",
      "meaning": "灵活地",
      "englishMeaning": "in a way that can change or be changed easily according to the situation",
      "pronunciation": "/ˈflɛksəbli/",
      "sentence": "perform actions on their behalf, flexibly and with minimal guidance",
      "translation": "代表他们执行操作，灵活且只需最少的指导",
      "paperTitle": "The Agentic Economy",
      "category": "GRE高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adverb",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284766",
      "id": 24
    },
    {
      "word": "landscape",
      "meaning": "景观，格局",
      "englishMeaning": "the general situation in which a particular activity takes place",
      "pronunciation": "/ˈlændskeɪp/",
      "sentence": "transforming the landscape of consumer-business interactions",
      "translation": "改变消费者-企业互动的格局",
      "paperTitle": "The Agentic Economy",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284769",
      "id": 25
    },
    {
      "word": "revolutionized",
      "meaning": "彻底改变",
      "englishMeaning": "completely changed something",
      "pronunciation": "/ˌrɛvəˈluːʃənaɪzd/",
      "sentence": "Generative AI has revolutionized the way we interact with technology",
      "translation": "生成式AI已经彻底改变了我们与技术互动的方式",
      "paperTitle": "The Agentic Economy",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284772",
      "id": 26
    },
    {
      "word": "productive",
      "meaning": "有生产力的",
      "englishMeaning": "achieving a lot; producing good results",
      "pronunciation": "/prəˈdʌktɪv/",
      "sentence": "making both consumers and businesses more productive",
      "translation": "使消费者和企业都更有生产力",
      "paperTitle": "The Agentic Economy",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284778",
      "id": 27
    },
    {
      "word": "traditional",
      "meaning": "传统的",
      "englishMeaning": "following ideas and methods that have existed for a long time",
      "pronunciation": "/trəˈdɪʃənl/",
      "sentence": "Consumers have traditionally faced high communication costs",
      "translation": "消费者传统上面临高昂的沟通成本",
      "paperTitle": "The Agentic Economy",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284781",
      "id": 28
    },
    {
      "word": "intermediaries",
      "meaning": "中介，中间人",
      "englishMeaning": "people or organizations that help other people or organizations to make agreements",
      "pronunciation": "/ˌɪntərˈmiːdiˌɛriz/",
      "sentence": "The Market Power of Digital Intermediaries",
      "translation": "数字中介的市场力量",
      "paperTitle": "The Agentic Economy",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284784",
      "id": 29
    },
    {
      "word": "consumers",
      "meaning": "消费者",
      "englishMeaning": "people who buy goods or services for their own use",
      "pronunciation": "/kənˈsjuːməz/",
      "sentence": "communication frictions between consumers and businesses",
      "translation": "消费者与企业之间的沟通摩擦",
      "paperTitle": "The Agentic Economy",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284787",
      "id": 30
    },
    {
      "word": "communication",
      "meaning": "沟通，交流",
      "englishMeaning": "the process of sharing information",
      "pronunciation": "/kəˌmjuːnɪˈkeɪʃən/",
      "sentence": "reduce the communication frictions",
      "translation": "减少沟通摩擦",
      "paperTitle": "The Agentic Economy",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284790",
      "id": 31
    },
    {
      "word": "economic",
      "meaning": "经济的",
      "englishMeaning": "related to trade, industry, and money",
      "pronunciation": "/ˌiːkəˈnɒmɪk/",
      "sentence": "Economic impact",
      "translation": "经济影响",
      "paperTitle": "The Agentic Economy",
      "category": "IELTS高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284793",
      "id": 32
    },
    {
      "word": "potential",
      "meaning": "潜力，可能性",
      "englishMeaning": "possible when the necessary conditions exist",
      "pronunciation": "/pəˈtɛnʃəl/",
      "sentence": "its potential to drastically reduce the communication frictions",
      "translation": "其大幅减少沟通摩擦的潜力",
      "paperTitle": "The Agentic Economy",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284797",
      "id": 33
    },
    {
      "word": "services",
      "meaning": "服务",
      "englishMeaning": "the providing of something that people need",
      "pronunciation": "/ˈsɜːvɪsɪz/",
      "sentence": "the introduction of entirely new products and services",
      "translation": "引入全新的产品和服务",
      "paperTitle": "The Agentic Economy",
      "category": "IELTS高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284800",
      "id": 34
    },
    {
      "word": "generative AI",
      "meaning": "生成式人工智能",
      "englishMeaning": "artificial intelligence that can create new content",
      "pronunciation": "/ˈdʒɛnərətɪv ˌeɪ ˈaɪ/",
      "sentence": "Generative AI has revolutionized the way we interact with technology",
      "translation": "生成式AI已经彻底改变了我们与技术互动的方式",
      "paperTitle": "The Agentic Economy",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284803",
      "id": 35
    },
    {
      "word": "AI agents",
      "meaning": "AI智能体",
      "englishMeaning": "artificial intelligence systems that can act autonomously",
      "pronunciation": "/ˌeɪ ˈaɪ ˈeɪdʒənts/",
      "sentence": "It has paved the way for AI agents that not only converse with users",
      "translation": "它为AI智能体铺平了道路，这些智能体不仅能与用户对话",
      "paperTitle": "The Agentic Economy",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284805",
      "id": 36
    },
    {
      "word": "assistant agent",
      "meaning": "助手智能体",
      "englishMeaning": "AI system that assists users in completing tasks",
      "pronunciation": "/əˈsɪstənt ˈeɪdʒənt/",
      "sentence": "every consumer has an assistant agent to communicate their preferences",
      "translation": "每个消费者都有一个助手智能体来传达他们的偏好",
      "paperTitle": "The Agentic Economy",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284808",
      "id": 37
    },
    {
      "word": "service agent",
      "meaning": "服务智能体",
      "englishMeaning": "AI system that provides services to users",
      "pronunciation": "/ˈsɜːvɪs ˈeɪdʒənt/",
      "sentence": "every business has service agents to interact with consumers",
      "translation": "每个企业都有服务智能体来与消费者互动",
      "paperTitle": "The Agentic Economy",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284811",
      "id": 38
    },
    {
      "word": "natural language",
      "meaning": "自然语言",
      "englishMeaning": "human languages as they are naturally spoken",
      "pronunciation": "/ˈnætʃrəl ˈlæŋɡwɪdʒ/",
      "sentence": "express their intent in free-form natural language",
      "translation": "以自由形式的自然语言表达意图",
      "paperTitle": "The Agentic Economy",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-08T19:11:55.284814",
      "id": 39
    }
  ],
  "timestamp": "2025-09-08T19:11:55.294433"
}

module.exports = vocabularyUpdate
