// 词汇更新数据
// 自动生成于: 2025-09-06T21:40:46.202808

const vocabularyUpdate = {
  "version": "20250906_214046",
  "vocabulary": [
    {
      "word": "plethora",
      "meaning": "过多，大量",
      "englishMeaning": "a large or excessive amount of something",
      "pronunciation": "/ˈpleθərə/",
      "sentence": "a plethora of open-source foundation models have emerged",
      "translation": "大量开源基础模型已经涌现",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "GRE高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.183969",
      "id": 1
    },
    {
      "word": "stringent",
      "meaning": "严格的，严厉的",
      "englishMeaning": "strict, precise, and exacting",
      "pronunciation": "/ˈstrɪndʒənt/",
      "sentence": "imposes uniquely stringent demands on AI systems",
      "translation": "对人工智能系统提出了独特的严格要求",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.183991",
      "id": 2
    },
    {
      "word": "intrinsic",
      "meaning": "固有的，本质的",
      "englishMeaning": "belonging naturally; essential",
      "pronunciation": "/ɪnˈtrɪnzɪk/",
      "sentence": "understand and capture the intrinsic laws",
      "translation": "理解并捕捉内在规律",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184000",
      "id": 3
    },
    {
      "word": "mitigate",
      "meaning": "减轻，缓和",
      "englishMeaning": "to make less severe, serious, or painful",
      "pronunciation": "/ˈmɪtɪɡeɪt/",
      "sentence": "To mitigate this gap and explore a step further",
      "translation": "为了缓解这一差距并进一步探索",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "GRE高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184008",
      "id": 4
    },
    {
      "word": "synergize",
      "meaning": "协同作用，增效",
      "englishMeaning": "to combine or cooperate to produce a greater effect",
      "pronunciation": "/ˈsɪnədʒaɪz/",
      "sentence": "to synergize the RL training on more than 1000 tasks",
      "translation": "协同推进超过1000个任务的强化学习训练",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184016",
      "id": 5
    },
    {
      "word": "comprehensive",
      "meaning": "全面的，综合的",
      "englishMeaning": "complete and including everything that is necessary",
      "pronunciation": "/ˌkɒmprɪˈhensɪv/",
      "sentence": "On comprehensive evaluation benchmarks",
      "translation": "在综合评估基准上",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184024",
      "id": 6
    },
    {
      "word": "foundation",
      "meaning": "基础",
      "englishMeaning": "the basis or groundwork of anything",
      "pronunciation": "/faʊnˈdeɪʃn/",
      "sentence": "open-source foundation models",
      "translation": "开源基础模型",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184033",
      "id": 7
    },
    {
      "word": "capability",
      "meaning": "能力，才能",
      "englishMeaning": "the power or ability to do something",
      "pronunciation": "/ˌkeɪpəˈbɪləti/",
      "sentence": "general understanding and reasoning capabilities",
      "translation": "通用理解和推理能力",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184041",
      "id": 8
    },
    {
      "word": "domain",
      "meaning": "领域，范围",
      "englishMeaning": "a specified sphere of activity or knowledge",
      "pronunciation": "/dəˈmeɪn/",
      "sentence": "scientific domains",
      "translation": "科学领域",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "TOEFL高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184048",
      "id": 9
    },
    {
      "word": "significant",
      "meaning": "显著的，重要的",
      "englishMeaning": "sufficiently great or important to be worthy of attention",
      "pronunciation": "/sɪɡˈnɪfɪkənt/",
      "sentence": "significantly outperforms open-source models",
      "translation": "显著优于开源模型",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184056",
      "id": 10
    },
    {
      "word": "transform",
      "meaning": "改变，转换",
      "englishMeaning": "to make a thorough or dramatic change in the form, appearance, or character of",
      "pronunciation": "/trænsˈfɔːrm/",
      "sentence": "far from sufficient for transforming scientific research",
      "translation": "远不足以变革科学研究",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184063",
      "id": 11
    },
    {
      "word": "fundamental",
      "meaning": "基础的，根本的",
      "englishMeaning": "forming a necessary base or core; of central importance",
      "pronunciation": "/ˌfʌndəˈmentl/",
      "sentence": "drive fundamental breakthroughs in human society",
      "translation": "推动人类社会的根本性突破",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184070",
      "id": 12
    },
    {
      "word": "multimodal",
      "meaning": "多模态的",
      "englishMeaning": "involving several different modes or methods",
      "pronunciation": "/ˌmʌltiˈməʊdl/",
      "sentence": "a scientific multimodal foundation model",
      "translation": "一个科学的多模态基础模型",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184077",
      "id": 13
    },
    {
      "word": "parameter",
      "meaning": "参数",
      "englishMeaning": "a numerical or other measurable factor forming one of a set that defines a system or sets the conditions of its operation",
      "pronunciation": "/pəˈræmɪtə(r)/",
      "sentence": "28 billion activated parameters and 241 billion total parameters",
      "translation": "280亿激活参数和2410亿总参数",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184084",
      "id": 14
    },
    {
      "word": "benchmark",
      "meaning": "基准，标准",
      "englishMeaning": "a standard or point of reference against which things may be compared",
      "pronunciation": "/ˈbentʃmɑːk/",
      "sentence": "On comprehensive evaluation benchmarks",
      "translation": "在综合评估基准上",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184091",
      "id": 15
    },
    {
      "word": "resource",
      "meaning": "资源",
      "englishMeaning": "a stock or supply of money, materials, staff, and other assets that can be drawn on by a person or organization in order to function effectively",
      "pronunciation": "/ˈriːsɔːs/",
      "sentence": "diverse but low-resource distributed scientific modalities",
      "translation": "多样但低资源分布的科学模态",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "IELTS高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184098",
      "id": 16
    },
    {
      "word": "optimization",
      "meaning": "优化",
      "englishMeaning": "the action of making the best or most effective use of a situation or resource",
      "pronunciation": "/ˌɒptɪmaɪˈzeɪʃn/",
      "sentence": "experimental design optimization",
      "translation": "实验设计优化",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184105",
      "id": 17
    },
    {
      "word": "Artificial General Intelligence (AGI)",
      "meaning": "通用人工智能",
      "englishMeaning": "The hypothetical ability of an intelligent agent to understand or learn any intellectual task that a human being can",
      "pronunciation": "/ˌɑːtɪˈfɪʃl ˈdʒenrəl ɪnˈtelɪdʒəns/",
      "sentence": "a step further toward Artificial General Intelligence (AGI)",
      "translation": "向通用人工智能（AGI）更进一步",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun phrase",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184112",
      "id": 18
    },
    {
      "word": "Mixture-of-Experts (MoE)",
      "meaning": "混合专家模型",
      "englishMeaning": "A neural network architecture that consists of multiple expert networks and a gating network that decides which expert to use for each input",
      "pronunciation": "/ˈmɪkstʃər əv ˈekspɜːrts/",
      "sentence": "Intern-S1 is a multimodal Mixture-of-Experts (MoE) model",
      "translation": "Intern-S1是一个多模态混合专家（MoE）模型",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun phrase",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184119",
      "id": 19
    },
    {
      "word": "Reinforcement Learning (RL)",
      "meaning": "强化学习",
      "englishMeaning": "A type of machine learning where an agent learns to make decisions by taking actions in an environment to achieve a goal, based on rewards and punishments",
      "pronunciation": "/ˌriːɪnˈfɔːrsmənt ˈlɜːrnɪŋ/",
      "sentence": "undergoes offline and then online reinforcement learning (RL)",
      "translation": "经历离线和在线强化学习（RL）",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun phrase",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184126",
      "id": 20
    },
    {
      "word": "pre-training",
      "meaning": "预训练",
      "englishMeaning": "The initial phase of training a model on a large dataset before fine-tuning on a specific task",
      "pronunciation": "/ˌpriːˈtreɪnɪŋ/",
      "sentence": "continually pre-trained on 5T tokens",
      "translation": "基于5T token进行了持续预训练",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184133",
      "id": 21
    },
    {
      "word": "reasoning",
      "meaning": "推理",
      "englishMeaning": "The process of thinking about something in a logical way in order to form a conclusion or judgment",
      "pronunciation": "/ˈriːzənɪŋ/",
      "sentence": "general understanding and reasoning capabilities",
      "translation": "通用理解和推理能力",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184141",
      "id": 22
    },
    {
      "word": "modality",
      "meaning": "模态",
      "englishMeaning": "A particular mode in which something exists or is experienced or expressed",
      "pronunciation": "/məʊˈdæləti/",
      "sentence": "diverse but low-resource distributed scientific modalities",
      "translation": "多样但低资源分布的科学模态",
      "paperTitle": "Intern-S1: A Scientific Multimodal Foundation Model",
      "category": "AI专业词汇",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184148",
      "id": 23
    },
    {
      "word": "progressive",
      "meaning": "渐进的，逐步的",
      "englishMeaning": "happening or developing gradually or in stages",
      "pronunciation": "/prəˈɡresɪv/",
      "sentence": "we adopt a progressive training strategy that starts with non-text-to-text rendering",
      "translation": "我们采用渐进式训练策略，从非文本到文本渲染开始",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184925",
      "id": 24
    },
    {
      "word": "substantially",
      "meaning": "实质上，大幅度地",
      "englishMeaning": "to a great or significant extent",
      "pronunciation": "/səbˈstænʃəli/",
      "sentence": "This curriculum learning approach substantially enhances the model's native text rendering capabilities",
      "translation": "这种课程学习方法显著增强了模型的原生文本渲染能力",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adverb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184933",
      "id": 25
    },
    {
      "word": "remarkable",
      "meaning": "显著的，非凡的",
      "englishMeaning": "worthy of attention; extraordinary",
      "pronunciation": "/rɪˈmɑːkəbl/",
      "sentence": "achieves remarkable progress on more challenging logographic languages like Chinese",
      "translation": "在更具挑战性的汉字等表意文字语言上取得了显著进展",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184938",
      "id": 26
    },
    {
      "word": "coherence",
      "meaning": "连贯性，一致性",
      "englishMeaning": "the quality of being logical and consistent",
      "pronunciation": "/kəʊˈhɪərəns/",
      "sentence": "where global semantics must be preserved during structural changes",
      "translation": "在结构变化期间必须保持全局语义",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "GRE高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184943",
      "id": 27
    },
    {
      "word": "challenge",
      "meaning": "挑战",
      "englishMeaning": "a task or situation that tests someone's abilities",
      "pronunciation": "/ˈtʃælɪndʒ/",
      "sentence": "To address the challenges of complex text rendering",
      "translation": "为解决复杂文本渲染的挑战",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184949",
      "id": 28
    },
    {
      "word": "strategy",
      "meaning": "策略",
      "englishMeaning": "a plan of action designed to achieve a long-term or overall aim",
      "pronunciation": "/ˈstrætədʒi/",
      "sentence": "we adopt a progressive training strategy",
      "translation": "我们采用渐进式训练策略",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "TOEFL高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184953",
      "id": 29
    },
    {
      "word": "framework",
      "meaning": "框架",
      "englishMeaning": "a basic structure underlying a system, concept, or text",
      "pronunciation": "/ˈfreɪmwɜːk/",
      "sentence": "we design a Producer-Consumer framework leveraging TensorPipe",
      "translation": "我们设计了利用TensorPipe的生产者-消费者框架",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "TOEFL高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184968",
      "id": 30
    },
    {
      "word": "enhance",
      "meaning": "增强",
      "englishMeaning": "intensify, increase, or further improve the quality, value, or extent of",
      "pronunciation": "/ɪnˈhɑːns/",
      "sentence": "To enhance image editing consistency",
      "translation": "为增强图像编辑一致性",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "IELTS高频词",
      "difficulty": "medium",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184974",
      "id": 31
    },
    {
      "word": "incorporate",
      "meaning": "包含，融合",
      "englishMeaning": "take in or contain something as part of a whole",
      "pronunciation": "/ɪnˈkɔːpəreɪt/",
      "sentence": "incorporates not only traditional text-to-image tasks but also image-to-image reconstruction",
      "translation": "不仅包含传统的文本到图像任务，还包括图像到图像重建",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184979",
      "id": 32
    },
    {
      "word": "evaluation",
      "meaning": "评估",
      "englishMeaning": "the making of a judgement about the amount, number, or value of something",
      "pronunciation": "/ɪˌvæljuˈeɪʃn/",
      "sentence": "We present a comprehensive evaluation of Qwen-Image across multiple public benchmarks",
      "translation": "我们在多个公共基准测试中对Qwen-Image进行了全面评估",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184984",
      "id": 33
    },
    {
      "word": "demonstrate",
      "meaning": "证明，展示",
      "englishMeaning": "clearly show the existence or truth of something by giving proof or evidence",
      "pronunciation": "/ˈdemənstreɪt/",
      "sentence": "demonstrating its strong capabilities in both image generation and editing",
      "translation": "展示了其在图像生成和编辑方面的强大能力",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "verb",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184987",
      "id": 34
    },
    {
      "word": "infrastructure",
      "meaning": "基础设施",
      "englishMeaning": "the basic physical and organizational structures and facilities needed for the operation of a society or enterprise",
      "pronunciation": "/ˈɪnfrəstrʌktʃə(r)/",
      "sentence": "scalable infrastructure optimization",
      "translation": "可扩展的基础设施优化",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "IELTS高频词",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184990",
      "id": 35
    },
    {
      "word": "diffusion-based",
      "meaning": "基于扩散的",
      "englishMeaning": "referring to models that use diffusion processes for data generation",
      "pronunciation": "/dɪˈfjuːʒən beɪst/",
      "sentence": "particularly with the advent of diffusion-based architectures",
      "translation": "特别是随着基于扩散的架构的出现",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184993",
      "id": 36
    },
    {
      "word": "text-to-image",
      "meaning": "文本到图像",
      "englishMeaning": "the task of generating images from textual descriptions",
      "pronunciation": "/tekst tuː ˈɪmɪdʒ/",
      "sentence": "encompassing both text-to-image generation (T2I)",
      "translation": "包含文本到图像生成（T2I）",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184996",
      "id": 37
    },
    {
      "word": "multi-task",
      "meaning": "多任务",
      "englishMeaning": "involving multiple related tasks in machine learning",
      "pronunciation": "/ˈmʌlti tɑːsk/",
      "sentence": "we introduce an improved multi-task training paradigm",
      "translation": "我们引入了改进的多任务训练范式",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "adjective",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.184999",
      "id": 38
    },
    {
      "word": "latent representations",
      "meaning": "潜在表示",
      "englishMeaning": "hidden or compressed representations of data in a neural network",
      "pronunciation": "/ˈleɪtənt ˌreprɪzenˈteɪʃənz/",
      "sentence": "effectively aligning the latent representations between Qwen2.5-VL and MMDiT",
      "translation": "有效对齐Qwen2.5-VL和MMDiT之间的潜在表示",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.185002",
      "id": 39
    },
    {
      "word": "curriculum learning",
      "meaning": "课程学习",
      "englishMeaning": "a training strategy that starts with easier examples and gradually increases difficulty",
      "pronunciation": "/kəˈrɪkjələm ˈlɜːnɪŋ/",
      "sentence": "This curriculum learning approach substantially enhances the model's capabilities",
      "translation": "这种课程学习方法显著增强了模型的能力",
      "paperTitle": "Qwen-Image Technical Report",
      "category": "AI专业词汇",
      "difficulty": "hard",
      "status": "learning",
      "studyCount": 0,
      "correctCount": 0,
      "lastStudyTime": null,
      "weeklyStudyCount": 0,
      "partOfSpeech": "noun",
      "source": "LLM提取",
      "extractedAt": "2025-09-06T21:40:46.185005",
      "id": 40
    }
  ],
  "timestamp": "2025-09-06T21:40:46.202808"
}

module.exports = vocabularyUpdate
